import type { LearningDashboard } from "@/types/learning";

const now = new Date().toISOString();

export const mockLearningDashboard: LearningDashboard = {
  as_of: now,
  closed_trade_count: 3,
  open_trade_count: 1,
  win_rate: 0.333,
  total_pnl_inr: -5150,
  profit_factor: 0.42,
  failure_memory_count: 3,
  adaptation_frozen: false,
  freeze_reason: null,
  module_attribution: [
    {
      strategy: "vega_scalping",
      trade_count: 1,
      wins: 0,
      losses: 1,
      scratches: 0,
      win_rate: 0,
      total_pnl_inr: -4200,
      expectancy_inr: -4200,
      weight: 0.92,
    },
    {
      strategy: "gamma_scalping",
      trade_count: 1,
      wins: 0,
      losses: 1,
      scratches: 0,
      win_rate: 0,
      total_pnl_inr: -3100,
      expectancy_inr: -3100,
      weight: 0.95,
    },
    {
      strategy: "simple_volatility",
      trade_count: 1,
      wins: 1,
      losses: 0,
      scratches: 0,
      win_rate: 1,
      total_pnl_inr: 2150,
      expectancy_inr: 2150,
      weight: 1.05,
    },
  ],
  recent_outcomes: [
    {
      outcome_id: "out_mock_001",
      trade_id: "trd_seed_tatasteel_001",
      underlying_symbol: "TATASTEEL",
      rank: 1,
      strategy: "vega_scalping",
      entry_mode: "standard",
      scenario_tag: "Scenario A: Clean Intraday IV Flush",
      primary_signal: "iv_z_score=-2.55 ≤ -2.0",
      score_at_entry: 0.91,
      confidence_at_entry: 0.88,
      outcome: "loss",
      realized_pnl_inr: -4200,
      exit_reason: "IV stop −3σ (N6.1)",
      opened_at: now,
      closed_at: now,
      failure_memory_id: "fm_seed_tatasteel_vega",
      config_snapshot_id: "defaults",
    },
  ],
  open_trades: [
    {
      trade_id: "trd_reliance_mock",
      underlying_symbol: "RELIANCE",
      rank: 2,
      strategy: "simple_volatility",
      entry_mode: "cheap_vol_mode",
      scenario_tag: "Scenario A: Normal Cheap-Vol Setup",
      primary_signal: "IV < GARCH",
      score: 0.82,
      confidence: 0.78,
      opened_at: now,
      config_snapshot_id: "defaults",
    },
  ],
  failure_memories: [
    {
      failure_id: "fm_seed_tatasteel_vega",
      trade_id: "trd_seed_tatasteel_001",
      underlying_symbol: "TATASTEEL",
      strategy: "vega_scalping",
      entry_mode: "standard",
      scenario_tag: "Scenario A: Clean Intraday IV Flush",
      primary_signal: "iv_z_score=-2.55 ≤ -2.0",
      market_summary:
        "TATASTEEL IV flush looked clean but stationarity broke mid-session.",
      loss_pnl_inr: -4200,
      exit_reason: "IV stop −3σ (N6.1)",
      lesson:
        "Deep IV flush on mid-cap steel names often continues when OI is thin — require higher OI or tighter session-time exit.",
      tags: ["vega_scalping", "iv_flush", "TATASTEEL"],
      closed_at: now,
    },
    {
      failure_id: "fm_seed_infy_gamma",
      trade_id: "trd_seed_infy_002",
      underlying_symbol: "INFY",
      strategy: "gamma_scalping",
      entry_mode: "earnings_gap_mode",
      scenario_tag: "Scenario A: Earnings Gap",
      primary_signal: "days_to_earnings=1",
      market_summary: "INFY earnings gap was muted; theta dominated.",
      loss_pnl_inr: -3100,
      exit_reason: "Quiet gap — theta bleed (M6)",
      lesson:
        "Earnings-gap gamma needs an implied-move floor; skip when options imply <1.5% move.",
      tags: ["gamma_scalping", "earnings", "INFY"],
      closed_at: now,
    },
  ],
  adaptation_history: [],
  learning_loop_notes: [
    "Every closed trade feeds module attribution and failure memory (§12).",
    "Pre-trade: similar failure contexts penalize confidence by −0.10 (§12.6).",
    "Failure memory entries: 3 (includes seeded historical losses).",
  ],
};
