import type { BotStatus, PendingDecision } from "@/types/decisions";

const now = Date.now();
const expires = new Date(now + 12 * 60 * 1000).toISOString();
const created = new Date(now - 3 * 60 * 1000).toISOString();

export const mockBotStatus: BotStatus = {
  execution_mode: "shadow",
  supervision_mode: "supervised",
  autonomy: "supervised",
  scheduler_mode: "active",
  regime: "event_vol",
  daily_pnl: 342.5,
  win_rate: 0.62,
  drawdown_pct: 3.2,
  portfolio_greeks: {
    total_delta: 0.04,
    total_gamma: 0.82,
    total_theta: -120.0,
    total_vega: 0.35,
  },
  circuit_breakers_active: [],
  pending_count: 0,
  one_trade_locked: false,
  kill_switch_armed: false,
  api_health: "ok",
};

export const mockPendingDecisions: PendingDecision[] = [
  {
    decision_id: "dec_20260705_001",
    signal_id: "sig_20260705_001",
    status: "pending",
    module: "gamma_scalping",
    underlying_symbol: "INTC",
    confidence: 0.82,
    regime: "event_vol",
    explanation:
      "Gamma hedge warranted: IV below GARCH forecast with earnings gap setup. Vega neutralized at entry; delta drift within tolerance.",
    rationale: "IV < GARCH; gap risk; vega neutral at entry",
    rag_citations: [
      { document: "Gamma Scalping", chapter: "Chapter 5", page: 132 },
      { document: "Volatility Trading", chapter: "Chapter 3", page: 48 },
    ],
    legs: [
      {
        leg_id: 1,
        type: "call",
        position: 10,
        strike: 60,
        expiration: "2026-07-18",
        delta: 0.52,
        gamma: 0.08,
        theta: -42.0,
        vega: 0.71,
        mid_price: 2.15,
      },
      {
        leg_id: 2,
        type: "call",
        position: -6,
        strike: 60,
        expiration: "2026-08-15",
        delta: -0.31,
        gamma: -0.04,
        theta: 18.0,
        vega: -0.85,
        mid_price: 3.42,
      },
      {
        leg_id: 3,
        type: "stock",
        position: -200,
        delta: -1.0,
        gamma: 0,
        theta: 0,
        vega: 0,
        mid_price: 60.5,
      },
    ],
    totals: {
      total_delta: 0.02,
      total_gamma: 1.4,
      total_theta: -420.0,
      total_vega: -0.1,
    },
    economics: {
      net_edge_after_costs: 18.4,
      margin_estimate: 4200,
      expected_gamma_pnl: 125.5,
      expected_theta_loss: -45.0,
      total_transaction_cost: 62.1,
      slippage_cap_bps: 50,
    },
    plan: {
      stop: "Gap rule: re-neutralize or flatten if Greeks drift beyond cost limits",
      target: "Close after earnings gap if gamma-theta breakeven exceeded",
      time_exit: "D+0 or D+1; close after gap unless breakeven paid",
    },
    event_risks: ["Earnings release tonight", "Term structure stable at entry"],
    failure_modes: [
      "Quiet market — theta dominates without movement",
      "Post-gap Greek drift — delta/vega neutrality lost",
      "Partial fill across three legs",
    ],
    strategy_context: {
      entry_mode: "earnings_gap_mode",
      iv_annualized: 35,
      garch_forecast: 38,
      gamma_theta_breakeven_pct: 0.96,
      term_structure_ok: true,
      vega_neutral_at_entry: true,
    },
    risk_gates: [
      { id: "feeds_fresh", label: "Bound data feeds fresh", status: "pass" },
      { id: "confidence", label: "Confidence ≥ 0.70", status: "pass", detail: "0.82" },
      { id: "rag_faith", label: "RAG faithfulness ≥ 0.85", status: "pass" },
      { id: "one_trade", label: "One-trade scope", status: "pass" },
      { id: "net_edge", label: "Net edge > 0 after costs", status: "pass", detail: "+$18.40" },
      { id: "margin", label: "Margin sufficient", status: "pass" },
      { id: "regime", label: "Regime classifier", status: "pass", detail: "event_vol" },
      { id: "liquidity", label: "Option liquidity / spread cap", status: "pass" },
      { id: "kill_switch", label: "Kill-switch inactive", status: "pass" },
      { id: "autonomous", label: "Autonomous execution", status: "pass", detail: "Auto-submit" },
    ],
    created_at: created,
    expires_at: expires,
    scenario_tag: "Scenario A: Earnings Gap",
    alternative_strategies: ["Simple vol rejected — IV path uncertain through event"],
  },
  {
    decision_id: "dec_20260705_002",
    signal_id: "sig_20260705_002",
    status: "pending",
    module: "stat_arb",
    underlying_symbol: "AMZN/FB",
    confidence: 0.76,
    regime: "low_vol_mean_reverting",
    explanation:
      "Residual at −2.1σ with economics aligned: same-sector mean reversion. 8 of 12 lookback windows cointegrated.",
    rationale: "Buy Y (AMZN), sell X (META); residual below −2σ",
    rag_citations: [
      { document: "Statistical Arbitrage by Cointegration", chapter: "Chapter 4", page: 89 },
    ],
    legs: [
      {
        leg_id: 1,
        type: "stock",
        position: 10,
        delta: 1.0,
        gamma: 0,
        theta: 0,
        vega: 0,
        mid_price: 2436.88,
      },
      {
        leg_id: 2,
        type: "stock",
        position: -118,
        delta: -1.0,
        gamma: 0,
        theta: 0,
        vega: 0,
        mid_price: 234.91,
      },
    ],
    totals: {
      total_delta: 0.0,
      total_gamma: 0,
      total_theta: 0,
      total_vega: 0,
    },
    economics: {
      net_edge_after_costs: 8420,
      margin_estimate: 519934,
      expected_gamma_pnl: 0,
      expected_theta_loss: 0,
      total_transaction_cost: 180,
      slippage_cap_bps: 5,
    },
    plan: {
      stop: "3σ from residual mean — stationarity may be failing",
      target: "Residual mean reversion",
      time_exit: "Half-life ~24 business days; close if exceeded",
    },
    event_risks: ["No earnings on either leg within 5 days"],
    failure_modes: [
      "Relationship breakdown — residual pushes through 3σ",
      "Rounding error on hedge ratio creates residual exposure",
      "Borrow cost on short leg increases",
    ],
    strategy_context: {
      residual_z_score: -2.1,
      hedge_ratio: 11.736,
      half_life_days: 24,
      cointegrated_windows: 8,
      economics_aligned: true,
      pair_y: "AMZN",
      pair_x: "META",
    },
    risk_gates: [
      { id: "feeds_fresh", label: "Bound data feeds fresh", status: "pass" },
      { id: "confidence", label: "Confidence ≥ 0.70", status: "pass", detail: "0.76" },
      { id: "economics", label: "Economics gate (Table SA-8)", status: "pass" },
      { id: "adf", label: "ADF / Engle-Granger confidence", status: "pass" },
      { id: "one_trade", label: "One-trade scope", status: "pass" },
      { id: "margin", label: "Margin sufficient", status: "warn", detail: "High notional — review size" },
      { id: "regime", label: "Regime classifier", status: "pass" },
      { id: "autonomous", label: "Autonomous execution", status: "pass", detail: "Auto-submit" },
    ],
    created_at: created,
    expires_at: expires,
    scenario_tag: "Scenario A: Same-Sector Mean Reversion",
    alternative_strategies: ["Vega scalping — no intraday IV flush signal"],
  },
];

/** Full decision log for the Decisions page (audit trail + pending). */
export const mockDecisionLog: PendingDecision[] = [
  {
    ...mockPendingDecisions[0],
    status: "approved",
    created_at: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(now - 5.75 * 60 * 60 * 1000).toISOString(),
  },
  {
    ...mockPendingDecisions[1],
    status: "rejected",
    created_at: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(now - 3.75 * 60 * 60 * 1000).toISOString(),
  },
  {
    decision_id: "dec_20260714_003",
    signal_id: "sig_20260714_003",
    status: "approved",
    module: "vega_scalping",
    underlying_symbol: "TATASTEEL",
    confidence: 0.88,
    regime: "high_iv_mean_reverting",
    explanation:
      "Intraday IV flushed −2.55σ vs 20-day baseline with liquid near-week OTM vertical; flatten same session per N6.1.",
    rationale: "IV z-score ≤ −2.0; OI ≥ threshold; same-day flatten required",
    rag_citations: [
      { document: "Volatility Trading", chapter: "Chapter 6", page: 201 },
    ],
    legs: [
      {
        leg_id: 1,
        type: "put",
        position: -20,
        strike: 160,
        expiration: "2026-07-17",
        delta: -0.22,
        gamma: -0.05,
        theta: 85.0,
        vega: -1.4,
        mid_price: 1.85,
      },
      {
        leg_id: 2,
        type: "put",
        position: 20,
        strike: 155,
        expiration: "2026-07-17",
        delta: 0.12,
        gamma: 0.03,
        theta: -40.0,
        vega: 0.9,
        mid_price: 0.95,
      },
    ],
    totals: {
      total_delta: -0.1,
      total_gamma: -0.02,
      total_theta: 45.0,
      total_vega: -0.5,
    },
    economics: {
      net_edge_after_costs: 2100,
      margin_estimate: 18500,
      expected_gamma_pnl: 0,
      expected_theta_loss: 0,
      total_transaction_cost: 420,
      slippage_cap_bps: 40,
    },
    plan: {
      stop: "IV z-score −3σ or Δ hedge drift beyond cost limit",
      target: "IV mean reversion to −0.5σ",
      time_exit: "Flatten by 15:15 IST same day",
    },
    event_risks: ["Thin OI on 155 put wing", "Steel complex correlated move"],
    failure_modes: [
      "Continued flush through −3σ",
      "Partial fill leaves naked short vega",
    ],
    strategy_context: {
      intraday_iv_z_score: -2.55,
      must_flatten_same_day: true,
      iv_annualized: 28,
      garch_forecast: 24,
    },
    risk_gates: [
      { id: "feeds_fresh", label: "Bound data feeds fresh", status: "pass" },
      { id: "confidence", label: "Confidence ≥ 0.70", status: "pass", detail: "0.88" },
      { id: "one_trade", label: "One-trade scope", status: "pass" },
      { id: "autonomous", label: "Autonomous execution", status: "pass", detail: "Auto-submit" },
    ],
    created_at: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(now - 25.75 * 60 * 60 * 1000).toISOString(),
    scenario_tag: "Scenario A: Clean Intraday IV Flush",
  },
  {
    decision_id: "dec_20260713_004",
    signal_id: "sig_20260713_004",
    status: "expired",
    module: "volatility",
    underlying_symbol: "NIFTY",
    confidence: 0.71,
    regime: "low_vol_mean_reverting",
    explanation:
      "Cheap-vol calendar candidate; approval window elapsed before human override closed — not submitted.",
    rationale: "IV < GARCH; term structure contango",
    rag_citations: [
      { document: "Volatility Trading", chapter: "Chapter 2", page: 31 },
    ],
    legs: [
      {
        leg_id: 1,
        type: "call",
        position: -5,
        strike: 24500,
        expiration: "2026-07-24",
        delta: -0.35,
        gamma: -0.02,
        theta: 120.0,
        vega: -2.1,
        mid_price: 185.5,
      },
      {
        leg_id: 2,
        type: "call",
        position: 5,
        strike: 24500,
        expiration: "2026-08-28",
        delta: 0.38,
        gamma: 0.015,
        theta: -70.0,
        vega: 3.4,
        mid_price: 312.0,
      },
    ],
    totals: {
      total_delta: 0.03,
      total_gamma: -0.005,
      total_theta: 50.0,
      total_vega: 1.3,
    },
    economics: {
      net_edge_after_costs: 8400,
      margin_estimate: 95000,
      expected_gamma_pnl: 0,
      expected_theta_loss: -2100,
      total_transaction_cost: 980,
      slippage_cap_bps: 25,
    },
    plan: {
      stop: "IV rises through GARCH +1σ",
      target: "IV expands toward GARCH forecast",
      time_exit: "7 DTE on front leg",
    },
    event_risks: ["RBI policy week", "Index weekly expiry pin"],
    failure_modes: ["Gap through short front leg", "Long back-month underperforms"],
    strategy_context: {
      entry_mode: "cheap_vol_mode",
      iv_annualized: 11.2,
      garch_forecast: 14.8,
      gamma_theta_breakeven_pct: 0.55,
    },
    risk_gates: [
      { id: "feeds_fresh", label: "Bound data feeds fresh", status: "pass" },
      { id: "confidence", label: "Confidence ≥ 0.70", status: "pass", detail: "0.71" },
      { id: "timeout", label: "Approval timeout", status: "fail", detail: "Expired" },
    ],
    created_at: new Date(now - 48 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(now - 47.75 * 60 * 60 * 1000).toISOString(),
    scenario_tag: "Scenario A: Normal Cheap-Vol Setup",
  },
  {
    decision_id: "dec_20260712_005",
    signal_id: "sig_20260712_005",
    status: "approved",
    module: "gamma_scalping",
    underlying_symbol: "INFY",
    confidence: 0.79,
    regime: "event_vol",
    explanation:
      "Pre-earnings gamma: IV cheap vs implied move; vega neutralized calendar with stock hedge.",
    rationale: "Earnings tomorrow; IV < GARCH; gap mode",
    rag_citations: [
      { document: "Gamma Scalping", chapter: "Chapter 5", page: 140 },
    ],
    legs: [
      {
        leg_id: 1,
        type: "call",
        position: 15,
        strike: 1620,
        expiration: "2026-07-17",
        delta: 0.48,
        gamma: 0.06,
        theta: -95.0,
        vega: 1.1,
        mid_price: 28.5,
      },
      {
        leg_id: 2,
        type: "call",
        position: -10,
        strike: 1620,
        expiration: "2026-08-28",
        delta: -0.42,
        gamma: -0.03,
        theta: 40.0,
        vega: -1.3,
        mid_price: 62.0,
      },
      {
        leg_id: 3,
        type: "stock",
        position: -150,
        delta: -1.0,
        gamma: 0,
        theta: 0,
        vega: 0,
        mid_price: 1618.4,
      },
    ],
    totals: {
      total_delta: 0.05,
      total_gamma: 0.9,
      total_theta: -550.0,
      total_vega: -0.2,
    },
    economics: {
      net_edge_after_costs: -3100,
      margin_estimate: 72000,
      expected_gamma_pnl: 180,
      expected_theta_loss: -95,
      total_transaction_cost: 1100,
      slippage_cap_bps: 45,
    },
    plan: {
      stop: "Quiet gap — flatten if move < 0.8%",
      target: "Post-gap gamma-theta breakeven",
      time_exit: "D+0 close after open auction",
    },
    event_risks: ["Muted earnings reaction", "Guidance overshadows EPS"],
    failure_modes: ["Theta dominates on quiet gap", "Post-gap Greek drift"],
    strategy_context: {
      entry_mode: "earnings_gap_mode",
      iv_annualized: 22,
      garch_forecast: 26,
      gamma_theta_breakeven_pct: 1.1,
      vega_neutral_at_entry: true,
    },
    risk_gates: [
      { id: "feeds_fresh", label: "Bound data feeds fresh", status: "pass" },
      { id: "confidence", label: "Confidence ≥ 0.70", status: "pass", detail: "0.79" },
      { id: "one_trade", label: "One-trade scope", status: "pass" },
      { id: "autonomous", label: "Autonomous execution", status: "pass", detail: "Auto-submit" },
    ],
    created_at: new Date(now - 72 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(now - 71.75 * 60 * 60 * 1000).toISOString(),
    scenario_tag: "Scenario A: Earnings Gap",
  },
  ...mockPendingDecisions,
];

export function getMockDecision(id: string): PendingDecision | undefined {
  return (
    mockDecisionLog.find((d) => d.decision_id === id) ??
    mockPendingDecisions.find((d) => d.decision_id === id)
  );
}
