import type { RiskSnapshot } from "@/types/risk";

export const mockRiskSnapshot: RiskSnapshot = {
  as_of: new Date().toISOString(),
  equity_inr: 1_000_000,
  starting_capital_inr: 1_000_000,
  reserved_margin_inr: 0,
  cash_inr: 1_000_000,
  realized_pnl: 0,
  unrealized_pnl: 0,
  session_pnl: 0,
  daily_pnl: 0,
  drawdown_pct: 0,
  win_rate: 0,
  open_positions: 0,
  portfolio_greeks: {
    total_delta: 0,
    total_gamma: 0,
    total_theta: 0,
    total_vega: 0,
  },
  greek_limits: [
    { greek: "Delta", key: "total_delta", current: 0, limit: 10_000, pct: 0 },
    { greek: "Gamma", key: "total_gamma", current: 0, limit: 5_000, pct: 0 },
    { greek: "Vega", key: "total_vega", current: 0, limit: 50_000, pct: 0 },
    { greek: "Theta", key: "total_theta", current: 0, limit: 50_000, pct: 0 },
  ],
  greeks_within_limits: true,
  greeks_failures: [],
  circuit_breakers: [
    {
      id: "max_drawdown",
      name: "Max Drawdown",
      current: 0,
      limit: 10,
      unit: "pct",
      pct: 0,
      tone: "safe",
      detail: "Circuit at ≤ 10% equity (§2.2 / §11.4.1)",
    },
    {
      id: "max_daily_loss",
      name: "Max Daily Loss",
      current: 0,
      limit: 20_000,
      unit: "inr",
      pct: 0,
      tone: "safe",
      detail: "2% of equity (§11.4.1)",
    },
    {
      id: "consecutive_losses",
      name: "Consecutive Losses",
      current: 0,
      limit: 5,
      unit: "count",
      pct: 0,
      tone: "safe",
      detail: "Pause discretionary entries at 5 (§11.4.1)",
    },
    {
      id: "feed_staleness",
      name: "Feed Staleness",
      current: 0,
      limit: 60,
      unit: "sec",
      pct: 0,
      tone: "safe",
      detail: "Quote stale threshold 60s",
    },
  ],
  circuit_breakers_active: [],
  feed_age_sec: null,
  events: [
    {
      level: "info",
      text: "Session ready. Initializing margin and circuit-breaker checks.",
      ts: new Date().toISOString(),
    },
  ],
  shared_kill_conditions: [
    "liquidity collapses or spreads blow out beyond limits",
    "a hedge leg becomes unavailable",
    "the model input is stale or clearly corrupted",
    "an earnings or news event appears that the setup was not designed to absorb",
    "required neutrality cannot be restored within cost limits",
    "residual delta or vega exposure exceeds portfolio limits",
    "the strategy's core assumption no longer holds",
  ],
  limits: {
    max_drawdown_pct: 10,
    max_daily_loss_pct: 2,
    max_consecutive_losses: 5,
    quote_stale_threshold_sec: 60,
    max_abs_total_delta: 10_000,
    max_abs_total_gamma: 5_000,
    max_abs_total_vega: 50_000,
    min_total_theta: -50_000,
  },
};
